### ISSUE TITLE
Github releases do not use different tags

### ISSUE THREAD

**Issue by hiddeninthesand** [stakira/OpenUtau#293] opened 2022-04-04 06:51 UTC
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

It's standard to use different tags/releases so install scripts can easily manage versions, as it is right now there is only a single binary release URL with no version indicator. Example at https://github.com/stakira/OpenUtau/releases/

### Explains how to reproduce the bug

1. Go to releases, and see that despite there being multiple versions, there is only a single tag + release.

### OS & Version

N/A

### Logs

N/A

**Comment by shniubobo** [comment] 2022-04-04 07:57
Duplicate of #269

**Comment by hiddeninthesand** [comment] 2022-04-04 08:25
My mistake

**Comment by hiddeninthesand** [comment] 2022-04-10 19:10
Actually, not my mistake. That issue was closed by the original opener since they could work around the limitations with their own API, but that doesn't actually resolve the issues with doing this. As I mentioned on that issue [here,](https://github.com/stakira/OpenUtau/issues/269#issuecomment-1087266519) it's still very difficult to package, since it means that unless the package is perfectly up to date, it will fail to build unless checksum verification is completely forgone, and if that happens it'll install as the wrong version. This is compounded by the fact that it's fairly difficult to tell at a glance if there has been a new update, since the single edited release model that is currently being used isn't picked up by Github notifications, and editing the release does not mark it as being released on the day of editing, so it'll always show up as the last release being on August 11th 2021. This means that unless I am constantly checking the releases (or using my own infrastructure specifically to check when OpenUtau has updated), the package will go out of date and break.

Removed from that, there's the secondary issue of many would-be users assuming the project is dead due to the last release being many moons ago. Please release normally :(

**Closed** 2023-06-24 02:48 UTC
Labels: no-issue-activity
