### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by xZlic3x** [stakira/OpenUtau#25] opened 2020-07-18 15:07 UTC
I dunno if I wrote that well, english is not my main language.

Welp, when I compile everything, it goes well. I think.
But when opening the .exe file, this pops up.
![openutau1](https://user-images.githubusercontent.com/58606134/87855509-1ca28600-c919-11ea-9c23-c4f766b1c592.png)
![openutau2](https://user-images.githubusercontent.com/58606134/87855511-1dd3b300-c919-11ea-827c-cd6655daf2cc.png)

I don't know anything about coding, I just followed [this thing](https://docs.microsoft.com/es-es/cpp/build/vscpp-step-2-build?view=vs-2019#run-your-code-in-a-command-window-issues) and I hope I did it fine.

Is there something I'm doing wrong, or any solution to this? I really wanna try OpenUtau.

**Comment by stakira** [comment] 2020-10-09 06:36
Duplicate of #28

**Closed by stakira** 2020-10-09 06:36 UTC
